// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBptVICgJcuzt-IcVIL_y-DxXrUujzmcQE',
    appId: '1:464987784089:web:61d6bf3abb4dd67d200908',
    messagingSenderId: '464987784089',
    projectId: 'food-delivery-app-kabarak',
    authDomain: 'food-delivery-app-kabarak.firebaseapp.com',
    storageBucket: 'food-delivery-app-kabarak.appspot.com',
    measurementId: 'G-BEBJ12E05E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC164zODPWE246k0wbsbkjqR47AMNLBTL0',
    appId: '1:464987784089:android:72fa4fc886166e3a200908',
    messagingSenderId: '464987784089',
    projectId: 'food-delivery-app-kabarak',
    storageBucket: 'food-delivery-app-kabarak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCqDTM7deD_-ooHCmwP_OeW9hFRjmbUQ',
    appId: '1:464987784089:ios:a6a34e2911574be6200908',
    messagingSenderId: '464987784089',
    projectId: 'food-delivery-app-kabarak',
    storageBucket: 'food-delivery-app-kabarak.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALCqDTM7deD_-ooHCmwP_OeW9hFRjmbUQ',
    appId: '1:464987784089:ios:a6a34e2911574be6200908',
    messagingSenderId: '464987784089',
    projectId: 'food-delivery-app-kabarak',
    storageBucket: 'food-delivery-app-kabarak.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptVICgJcuzt-IcVIL_y-DxXrUujzmcQE',
    appId: '1:464987784089:web:2b1714fbdfdaf57a200908',
    messagingSenderId: '464987784089',
    projectId: 'food-delivery-app-kabarak',
    authDomain: 'food-delivery-app-kabarak.firebaseapp.com',
    storageBucket: 'food-delivery-app-kabarak.appspot.com',
    measurementId: 'G-CP9D0Y9RD4',
  );

}